rabbitmq:
  image: rabbitmq:management
  container_name: sample-rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - "RABBITMQ_DEFAULT_USER=user"
    - "RABBITMQ_DEFAULT_PASS=password"
